version: '3.8'

services:
  app:
    build: ./api-gateway
    ports:
      - "3000:3000"
env_file: ./api-gateway/.env
depends_on:
- redis
- rabbitmq

environment:
    - REDIS_URL=redis://redis:6379
    - RABBITMQ_URL=amqp://rabbitmq:5672


user-service:
      build: ./user-service
      ports:
        - "3001:3001"
      env_file: ./user-service/.env
      depends_on:
        - rabbitmq
        - redis
      environment:
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - REDIS_URL=redis://redis:6379

post-service:
      build: ./post-service
      ports:
        - "3002:3002"
      env_file: ./post-service/.env
      depends_on:
        - rabbitmq
        - redis
      environment:
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - REDIS_URL=redis://redis:6379

media-service:
      build: ./media-service
      ports:
        - "3003:3003"
      env_file: ./media-service/.env
      depends_on:
        - rabbitmq
        - redis
      environment:
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - REDIS_URL=redis://redis:6379



redis:
    image: redis:alpine
    ports:
      - "6379:6379"

rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q","ping"]  
        interval: 30s
        timeout: 10s
        retries: 8



     



    

